services:
  mysql:
    container_name: homework.local.db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: homework
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"